newer examples (need feedback)
nftlabs/nftlabs-python-sdk-example pull request #1
Opened 2021-10-27 19:31 UTC by ayshptk

2021-10-30 18:16 UTC, jnsdls commented on app.py
> +# This is your wallet's private key, you can find them in your wallet. This will be used to interact with the contract
should call out here that you should never *publish* your private key anywhere

2021-10-30 18:19 UTC, jnsdls commented on currency.py
> +currency_module.mint(40 * 10 ** 18)
not sure how the other SDKs handle this right now, but it would probably be easier to explain to let people pass the "amount" and "decimals" (optionally, default to 10^18) separately, so the function signature would end up being something like:
`currency_module.mint(40, 18)` (and behind the scenes it does what you have here)

2021-10-30 18:20 UTC, jnsdls commented on currency.py
> +currency_module.mint(40 * 10 ** 18)
or optionally it could just be `currency_module.mint(40)` (which would default the decimals to `18`)

2021-10-30 18:20 UTC, jnsdls commented on currency.py
> +print(nft_module.get(27))
what does this like do?

2021-10-30 18:25 UTC, jnsdls commented
these are good examples, I would say in general be *more* explicit in the comments, think of people who see this as people who may never have interacted with web3 or have *very* limited exposure and most will definitely not have interacted with our sdk(s) before, so it makes sense to be a bit more verbose, use more words to describe. just an example:
in the example that lists a previously minted NFT on a market, we'll likely want to add some explanation of why you need to pass a currency contract etc, which (coming from a web2 world) is not immediately obvious. Once we have a better (general) documentation around all of these features we can probably just link to that for more details, but for now I'd say just describe it in more detail instead of just saying "here's what you have to do"

Obviously any examples with any description and explanation at all is better than none / less, so this is really just feedback on how to make it **even** better, not something I think would be required to ship this.

2021-10-30 20:34 UTC, ayshptk commented on app.py
> +# This is your wallet's private key, you can find them in your wallet. This will be used to interact with the contract
makes sense

2021-10-31 02:49 UTC, jakeloo requested changes

2021-10-31 02:49 UTC, jakeloo commented on app.py
> +. Never share them with anyone!sdk.set_private_key(os.getenv("PKEY"))
comment cut off?

2021-10-31 02:49 UTC, jakeloo commented on collection.py
> +collection.create(CollectionMetadata(id=1, creator="0xf16851cb58F3b3881e6bdAD21f57144E9aCf602E", supply=1, metadata=NftMetadata(name='example', description='example nft!', image='ipfs://bafkreige6wt2
When you create a collection, i don't think you need to pass in:
`id` and ` creator`. For NftMetadata: don't pass in `id=32` and `uri=`

2021-10-31 02:49 UTC, jakeloo commented on collection.py
> +print(collection.create_and_mint(CollectionMetadata(id=1, creator="0xf16851cb58F3b3881e6bdAD21f57144E9aCf602E", supply=1, metadata=NftMetadata(name='example', description='example nft!', image='ipfs:
same from above.

`create` and `create_and_mint` should not take in `id`, `creator` and `uri`

2021-10-31 02:49 UTC, jakeloo commented on currency.py
> +# This is your wallet's private key, you can find them in your wallet. This will be used to interact with the contract. Never share them with anyone!sdk.set_private_key(os.getenv("PKEY"))
i think the `sdk.set_private_key` should be next line after the comment. 
also make it more obvious by adding: `WARNING: do not share your private key with anyone`.

2021-10-31 02:49 UTC, jakeloo commented on currency.py
> +currency_module.mint(40 * 10 ** 18)
unfortunately this would mean breaking changes for all sdk. do you have a better name for `mintX` / `mint_X` that is more explicit? We should implement across all sdk i think.

i think we should keep `mint` without decimals placed multiplied into it because then it'd be standard with the smart contract and other library -- for people that already picked up ethers.js / eth development. there'd be no cognitive overhead of trying to forget and relearn + switching it up.

2021-10-31 02:49 UTC, jakeloo commented on currency.py
> +# This is your wallet's private key, you can find them in your wallet. This will be used to interact with the contract. Never share them with anyone!sdk.set_private_key(os.getenv("PKEY"))
the WARNING should go in all files

2021-11-01 10:00 UTC, jakeloo requested changes

2021-11-02 06:40 UTC, ayshptk commented on market.py
> +print(market_module.list(ListArg(asset_contract="0x5a5D758636e44767afAc67184B2249F5DBcACb8f", token_id=11, currency_contract="0x75b37A3EDB89bedF68D7866e4c539f914F7A985c", price_per_token=500000000000
damnn fff

2021-11-03 01:28 UTC, jakeloo requested changes

2021-11-03 01:28 UTC, jakeloo commented on nft.py
> +print(nft_module.mint(MintArg(name="example", description="example nft!", image_uri="ipfs://QmdFeKxt6FJUNvaGgzYuYNRbpNWyHxP2PFzjsgPf1eD2Jf", properties={})))
i think this should be `image` and not `image_uri` right?

2021-11-03 01:28 UTC, jakeloo commented on market.py
> +market_module.set_market_fee_bps(10)
10% = 1_000. 
bps = basis points, max bps = 10_000 = 100%.

2021-11-03 19:17 UTC, ayshptk commented on nft.py
> +print(nft_module.mint(MintArg(name="example", description="example nft!", image_uri="ipfs://QmdFeKxt6FJUNvaGgzYuYNRbpNWyHxP2PFzjsgPf1eD2Jf", properties={})))
<img width="456" alt="Screenshot 2021-11-04 at 12 47 47 AM" src="https://user-images.githubusercontent.com/62694274/140177923-23c2d025-0986-4d5b-b60b-098fc6c5c7d2.png">

2021-11-03 20:12 UTC, jakeloo commented on nft.py
> +print(nft_module.mint(MintArg(name="example", description="example nft!", image_uri="ipfs://QmdFeKxt6FJUNvaGgzYuYNRbpNWyHxP2PFzjsgPf1eD2Jf", properties={})))
this should be `image`  can we fix it in the sdk?

2021-11-03 21:09 UTC, merged